import Head from 'next/head';
import { forwardRef } from 'react';
import Navbar, { NAV_PADDINGX_CLASSNAME } from './Navbar';

export interface LayoutProps {
  children: any;
  title?: string;
  ref: any;
}

const Layout = forwardRef<HTMLDivElement, LayoutProps>(({ title, children }: LayoutProps, ref) => {
  return (
    <div ref={ref} className="min-h-[100vh] max-w-[1400px] mx-auto">
      <Head>
        <title>{title || 'Free Things Map'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={NAV_PADDINGX_CLASSNAME}>
        {children}
      </main>
    </div>
  )
});

Layout.displayName = 'Layout';

export default Layout;
